/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export { }

declare module 'vue' {
  interface ComponentCustomProperties {
    $CONFIG: typeof import('@/config/index')['default']
    $TOOL: typeof import('@/utils/tool')['default']
    $HTTP: typeof import('@/utils/request')['default']
    $API: typeof import('@/api')['default']
    $AUTH: typeof import('@/utils/permission')['permission']
    $ROLE: typeof import('@/utils/permission')['rolePermission']
  }
}
