/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    ScTable: typeof import('@/components/scTable/index.vue')['default']
    ScTableColumn: typeof import('@/components/scTable/column')['default']
    ScFilterBar: typeof import('@/components/scFilterBar/index.vue')['default']
    ScUpload: typeof import('@/components/scUpload/index.vue')['default']
    ScUploadMultiple: typeof import('@/components/scUpload/multiple.vue')['default']
    ScUploadFile: typeof import('@/components/scUpload/file.vue')['default']
    ScFormTable: typeof import('@/components/scFormTable/index.vue')['default']
    ScTableSelect: typeof import('@/components/scTableSelect/index.vue')['default']
    ScPageHeader: typeof import('@/components/scPageHeader/index.vue')['default']
    ScSelect: typeof import('@/components/scSelect/index.vue')['default']
    ScDialog: typeof import('@/components/scDialog/index.vue')['default']
    ScForm: typeof import('@/components/scForm/index.vue')['default']
    ScTitle: typeof import('@/components/scTitle/index.vue')['default']
    ScWaterMark: typeof import('@/components/scWaterMark/index.vue')['default']
    ScQrCode: typeof import('@/components/scQrCode/index.vue')['default']
    ScStatusIndicator: typeof import('@/components/scMini/scStatusIndicator.vue')['default']
    ScTrend: typeof import('@/components/scMini/scTrend.vue')['default']
  }
}
